Adding support for new 1.1 switchbot API version
jonghwanhyeon/python-switchbot pull request #13
Opened 2022-09-19 19:07 UTC by edsaavedra84

Also adding Lock device supprot with exact method entries

2022-09-20 02:56 UTC, jonghwanhyeon commented on README.md
> +import random
```suggestion
import time
import hashlib
import hmac
import base64

from switchbot import SwitchBot
```

2022-09-20 03:13 UTC, jonghwanhyeon commented on switchbot/__init__.py
> +        self.client = SwitchBotClient(token, ver, secret, nonce)
```suggestion
    def __init__(self, token: str, secret: str, nonce: str = ''):
        self.client = SwitchBotClient(token, secret, nonce)        
```

2022-09-20 03:15 UTC, jonghwanhyeon commented on switchbot/client.py
> +import base64
import base64
import hashlib
import hmac
import time

import humps
import requests

2022-09-20 03:15 UTC, jonghwanhyeon commented on switchbot/client.py
> +import base64
```suggestion
import base64
import hashlib
import hmac
import time

import humps
import requests
```

2022-09-20 03:16 UTC, jonghwanhyeon commented on switchbot/client.py
> +    }
```suggestion
switchbot_host = 'https://api.switch-bot.com/v1.1'
```

2022-09-20 03:17 UTC, jonghwanhyeon commented on switchbot/client.py
> +    def __init__(self, token: str, ver: str = None, secret: str = None, nonce: str = None):
```suggestion
    def __init__(self, token: str, secret: str, nonce: str = ''):
```

2022-09-20 03:24 UTC, jonghwanhyeon commented on switchbot/client.py
> +        self.session.headers['t'] = '{}'.format(t)
```suggestion

        timestamp = int(round(time.time() * 1000))
        string_to_sign = f'{token}{timestamp}{nonce}'

        string_to_sign = bytes(string_to_sign, 'utf-8')
        secret = bytes(secret, 'utf-8')
        sign = base64.b64encode(hmac.new(secret, msg=string_to_sign, digestmod=hashlib.sha256).digest())

        self.session.headers['Authorization'] = token
        self.session.headers['t'] = str(timestamp)
        self.session.headers['sign'] = sign
        self.session.headers['nonce'] = nonce
```

2022-09-20 03:24 UTC, jonghwanhyeon commented on switchbot/client.py
> +        url = f'{switchbot_hosts[self.ver]}/{path}'
```suggestion
        url = f'{switchbot_host}/{path}'
```

2022-09-20 03:26 UTC, jonghwanhyeon commented on setup.py
> +    version='2.1.1',
```suggestion
    version='2.2.0',
```

2022-09-20 03:32 UTC, jonghwanhyeon commented on README.md
```suggestion

### Devices
```python
import uuid

from switchbot import SwitchBot

# To get the token and secret, please refer to https://github.com/OpenWonderLabs/SwitchBotAPI#getting-started
your_switch_bot_token = '98a6732b2ac256d40ffab7db31a82f518969f4d1a64eadff581d45e902327b7c577aa6ead517bda589c19b4ca0b2599b'
your_switch_bot_secret = '222cdc22f049d111c5d0071c131b8b77'
switchbot = SwitchBot(token=your_switch_bot_token, secret=your_switch_bot_secret, nonce=str(uuid.uuid4()))
```

2022-09-20 03:34 UTC, jonghwanhyeon commented on README.md
According to the official document, they seem to suggest using uuid as nonce.

2022-09-20 03:38 UTC, jonghwanhyeon requested changes
Thanks for your contribution! Because SwitchBot API version has been officially updated to 1.1, I think it is better to support only that API and bump up the version to 2.2.0.

2022-09-21 22:27 UTC, edsaavedra84 commented
> Thanks for your contribution! Because SwitchBot API version has been officially updated to 1.1, I think it is better to support only that API and bump up the version to 2.2.0. Could you please check my suggestions?

I think you are right and I agree with the proposed changes. 

More than glad to help!

2022-09-26 07:52 UTC, merged

2022-10-15 02:28 UTC, jonghwanhyeon commented
Hello,

I have a question related to Issue #14 because I don't have SwitchBot Lock device 😢 .

In your pull request, you assigned `Lock.device_type_for` to `"Lock"`. However, according to [the official document](https://github.com/OpenWonderLabs/SwitchBotAPI#lock-1), it seems `"Smart Lock"` rather than `"Lock"`.

If possible, could you check which one is correct?

2022-11-10 20:39 UTC, edsaavedra84 commented
> Hello,
> 
> I have a question related to Issue #14 because I don't have SwitchBot Lock device 😢 .
> 
> In your pull request, you assigned `Lock.device_type_for` to `"Lock"`. However, according to [the official document](https://github.com/OpenWonderLabs/SwitchBotAPI#lock-1), it seems `"Smart Lock"` rather than `"Lock"`.
> 
> If possible, could you check which one is correct?

I am so sorry! I just saw the message.

It seems you already took care of that!